### ISSUE TITLE
Trees not spawning in the biomes

### ISSUE THREAD

**Issue by PinkBunny8** [TerraformersMC/Traverse#100]
hi, so I've recently found out that none of the trees in the mod are spawning in the world even tho I still gey the biomes. I run the mod with a bunch of different mods and it was working fine before but now its not. I still have access to the wood in creative

**Comment by gniftygnome** [comment]
Can you provide the game logs?

**Comment by Pankine** [comment]
this happened to me too, but restarting the game fixed it

**Comment by gniftygnome** [comment]
I'd like to get some kind of idea when it happens, so logs and pretty much any kind of info you might have about anything you might have done differently which might give me an idea what goes wrong would be great.  F.e. upgrading/adding/removing our or other mods, configuration changes, getting disconnecting from a server game and then reconnecting without restarting your client first ... etc.  Anything like that might give me an idea where to look.

**Comment by gniftygnome** [comment]
I've tracked down this bug in Biolith and will be releasing an update to Traverse for Minecraft 1.20 to fix it.

**Comment by PinkBunny8** [comment]
Hey, sorry I have been taking a break from all the modded minecraft stuff. I was removing and adding mods and playing around with them, so that could of been an issue aswell, but thank you so much for looking into it and fixing it
