### ISSUE TITLE
Placeholder biome generation

### ISSUE THREAD

**Issue by DavidGmc18** [TerraformersMC/Traverse#107]
When world-gen terraformer mod and mods utilizing Terrablender for biomes are present in certain scenarios (depending on the exact mod that requires Terrablender), terrablender:deferred_placeholder can generate. This bug can be reproduced using Terrablender, Traverse, and Nature Arise on Minecraft Fabric 1.20.4. From my investigation, it seems to occur on Minecraft versions 1.20 and newer, but I cannot confirm this definitively as I have not investigated that far. More details can be found in the issue reported to Terrablender: [Terrablender Issue-Placeholder biome generating #140](https://github.com/Glitchfiend/TerraBlender/issues/140).

**Comment by gniftygnome** [comment]
I've moved this to [Biolith issue #9](https://github.com/TerraformersMC/Biolith/issues/9).  Any mod which uses TB methods involving temporary selection of the placeholder biome will see this issue in combination with any mod using Biolith for biome placement.  There will be a new Biolith release soon to address this issue, then re-releases of 1.20+ versions of our mods.

**Comment by gniftygnome** [comment]
This should be resolved in Traverse 7.0.11, 7.1.2, and 7.2.0.  (Likewise the latest Terrestria and Cinderscapes releases.)
