### ISSUE TITLE
Biome tags not getting sent serialized to the client correctly

### ISSUE THREAD

**Issue by Mangraz** [TerraformersMC/Traverse#108]
That's the reason the dev of Antique Atlas gave for Traverse biomes not showing up properly on the map.
![grafik](https://github.com/TerraformersMC/Traverse/assets/95761308/08dfcbea-e814-45ad-8a1b-326b93a9cef7)

**Comment by Mangraz** [comment]
Nature's Compass however is reading tags just fine. Also Antique Atlas has the same issues with BetterNether and BetterEnd. Might be something on their end after all? [Here](https://github.com/sisby-folk/antique-atlas/issues/24) is the issues on their repo.

**Comment by gniftygnome** [comment]
Looks like they're working on it.  :crossed_fingers:

**Comment by sisby-folk** [comment]
problem on our end! fallback registration was just running before tags were sent - fixed now, you can close this.

**Comment by gniftygnome** [comment]
Awesome!
