### ISSUE TITLE
[Minecraft 1.21][Traverse v8.0.0-beta.3] Bug with Fir door - doesn't drop on breaking.

### ISSUE THREAD

**Issue by FoketzoRAI** [TerraformersMC/Traverse#115]
For some reason Fir door doesn't drop on breaking.

Traverse v8.0.0-beta.3 for 1.21-pre4
Minecraft 1.21
Fabric loader - 0.15.11

![image](https://github.com/TerraformersMC/Traverse/assets/32650781/b51ececb-7fe0-4b27-a8b0-cdef548ca91a)

Placed Fir door.
![2024-06-16_17 11 43](https://github.com/TerraformersMC/Traverse/assets/32650781/259e9421-f771-4ebf-a451-2255695c9c09)

Destroyed fir door with axe.
![2024-06-16_17 11 46](https://github.com/TerraformersMC/Traverse/assets/32650781/b3b48a98-c81f-409f-b48d-f12bd4297916)

**Comment by gniftygnome** [comment]
Thanks for reporting.  This will be fixed in the next release.

**Comment by gniftygnome** [comment]
Fixed in Traverse v8.0.0 for 1.21.
