### ISSUE TITLE
Crash when starting server 20w10a. (NoSuchMethodError)

### ISSUE THREAD

**Issue by paperdev-code** [TerraformersMC/Traverse#18]
[latest.log](https://github.com/TerraformersMC/Traverse/files/4318652/latest.log)
The associated log file.
`Caused by: java.lang.NoSuchMethodError: net.minecraft.class_2338$class_2339.<init>(Lnet/minecraft/class_2338;)V
	at com.terraformersmc.terraform.feature.FallenLogFeature.generate(FallenLogFeature.java:38) ~[f7362fae-fc0c-4d3e-9b56-c52c55da8a6c.jar:?]`

**Comment by Prospector** [comment]
Updated to 20w15a a couple days ago
