### ISSUE TITLE
Fir doors gets duplicated when you break them

### ISSUE THREAD

**Issue by Th3Glitch510** [TerraformersMC/Traverse#21]
I found this bug while playing RLCraft, you just need to place a fir door and break it, when you pick it up you will have 2 fir doors instead of 1, no matter which weapon you use.

Mod Version: 1.5
Java version: 1.8.0_241-b07
Thanks for the attention.

**Comment by NeusFear** [comment]
RLCraft uses Traverse Legacy likely. or an old version of traverse. Either way, this is the Fabric version of traverse, not the forge versions' repository. If you would like to report this to the forge version you can do so here: https://github.com/MysticMods/Traverse/issues
