### ISSUE TITLE
20w16a Crash

### ISSUE THREAD

**Issue by TerraSpecOp** [TerraformersMC/Traverse#22]
Disabled all other mods

https://paste.ee/p/YyRHN

**Comment by ghost** [comment]
I am getting the same error on the 20w16a server.

https://gist.github.com/takidelfin/855f6fdfc61555dd20d2a59650aaa848

**Comment by TerraSpecOp** [comment]
> I am getting the same error on the 20w16a server.
> 
> https://gist.github.com/takidelfin/855f6fdfc61555dd20d2a59650aaa848

Update to the new version. It works

**Comment by ghost** [comment]
> > I am getting the same error on the 20w16a server.
> > 
> > https://gist.github.com/takidelfin/855f6fdfc61555dd20d2a59650aaa848
> 
> Update to the new version. It works

Yeah, I know :) 

Thanks!
