### ISSUE TITLE
Conflict with Demeter

### ISSUE THREAD

**Issue by Neubulae** [TerraformersMC/Traverse#24]
https://pastebin.com/MRFp7R66
https://github.com/Wtoll/demeter/issues/14

**Comment by Neubulae** [comment]
[crash-2020-05-15_19.26.08-client.txt](https://github.com/TerraformersMC/Traverse/files/4634086/crash-2020-05-15_19.26.08-client.txt)

**Comment by Linguardium** [comment]
see https://github.com/TerraformersMC/Terraform/issues/10

**Comment by NeusFear** [comment]
duplicate of https://github.com/TerraformersMC/Terraform/issues/10
