### ISSUE TITLE
[MC: 1.15.2, version 2.1.14] Colored Flames Integration IllegalAccessError; crash on startup.

### ISSUE THREAD

**Issue by lizfinite** [TerraformersMC/Traverse#26]
With the most recent update, colored flames integration seems to be causing a conflict. 

I wasn't sure if this was something they need to fix on their end due to changes, or a bug I should post here. 
If the latter is the case then here is the log with just version 2.1.14, fabric API 0.10.8+build.310 and Colored Flames (https://www.curseforge.com/minecraft/mc-mods/colored-flames) 1.19r1:
https://pastebin.com/KWnHDF6R

**Comment by Prospector** [comment]
Hmm, that really isn't how they should be doing integration. It'd be much better (and could be dep-less) if they got the block from the registry using the block id. Really, it could all be data driven even. Nothing I can do from my end.
