### ISSUE TITLE
1.16-pre6[Stacktrace: 	at com.terraformersmc.traverse.feature.FallenTrunkPlacer.placeTrunkBlock(FallenTrunkPlacer.java:39)]

### ISSUE THREAD

**Issue by SDUBZ** [TerraformersMC/Traverse#27]
traverse: traverse-2.2.7+build.17

[latest.log](https://github.com/TerraformersMC/Traverse/files/4787150/latest.log)
[crash-2020-06-17_00.29.54-server.txt](https://github.com/TerraformersMC/Traverse/files/4787154/crash-2020-06-17_00.29.54-server.txt)

**Comment by ghost** [comment]
Hi, we love that you’ve been enjoying Traverse and appreciate you bringing this to our attention. At the moment Traverse is only officially built to support 1.16-pre2, and while in most cases prerelease versions are similar enough to allow mod usage on newer versions, in this case it appears that a minor change between prerelease versions has broken compatibility. We’re looking into a fix and are hoping to push a version to address this issue whether it’s on 1.16-pre6 or 1.16 proper, as it appears to be just around the corner. In the meantime try temporarily downgrading to 1.16-pre2 and let us know if you experience any other issues.

**Comment by Prospector** [comment]
Traverse v2.2.8 should work on 1.16-pre7
