### ISSUE TITLE
Nether Portal Generation in the Overworld

### ISSUE THREAD

**Issue by SilentButBreadly** [TerraformersMC/Traverse#31]
It would seem that nether portals do not generate in Traverse biomes in 1.16, a feature now implemented in vanilla 1.16 biomes. If such a feature could be added to Traverse it would be a nice addition to the mod.

**Comment by coderbot16** [comment]
Relevant PR: https://github.com/TerraformersMC/Traverse/pull/32

**Comment by Prospector** [comment]
Added in v2.2.13
