### ISSUE TITLE
Reloading a world after placing a fir boat will cause the game to crash.

### ISSUE THREAD

**Issue by SuitedLlama** [TerraformersMC/Traverse#35]
This seems to be a semi-reproducible game-breaking issue. It does not happen every single time.

Place a boat, leave the world, then join again. If the game does not crash, re-attempt on a new world until it does. 

Once it does happen the world is bricked permanently without using 3rd party map editors to remove the entity. 

The crash report probably isn't that helpful since it doesn't have mappings, but I'll include it anyway. I believe this has something to do with the tick method in the BoatEntity class. 

Here's a crashlog with no other mods installed:
[traverse-crash.txt](https://github.com/TerraformersMC/Traverse/files/5045173/traverse-crash.txt)

**Comment by coderbot16** [comment]
Fixed in 3.0.0.
