### ISSUE TITLE
needs an update for 1.16.2

### ISSUE THREAD

**Issue by Nathan22211** [TerraformersMC/Traverse#36]
I was using version 2.2.9+build.19 in a dev environment, but this is probably the case for the curse version

**Comment by Wtoll1** [comment]
Yes, all of our mods are going to have to be specially updated for 1.16.2. Mojang entirely rewrote the way biomes work when they added the ability to have datapack world generation. This update is likely going to take a lot longer than all of the previous ones, I would just recommend staying on 1.16.1. I don’t even know if our 1.16.2 update is really even going to come out before 1.17 snapshots, but we’re trying our hardest.

**Comment by ghost** [comment]
Yes, all of our mods are going to have to be specially updated for 1.16.2. Mojang entirely rewrote the way biomes work when they added the ability to have datapack world generation. This update is likely going to take a lot longer than all of the previous ones, I would just recommend staying on 1.16.1. I don't even know if our 1.16.2 update is really even going to come out before 1.17 snapshots, but we're trying our hardest.

**Comment by Prospector** [comment]
The beta is now out
