### ISSUE TITLE
crashes after updating to 2.2.15

### ISSUE THREAD

**Issue by slugzz** [TerraformersMC/Traverse#37]
i updated my fabric installer from 0.9.0 to 0.9.1 and updated traverse from 2.2.14 to 2.2.15
i tried 2.2.15 with the 0.9.0 fabric installer and it gives the same crash
[crash-2020-08-16_17.03.29-server.txt](https://github.com/TerraformersMC/Traverse/files/5081373/crash-2020-08-16_17.03.29-server.txt)

**Comment by Prospector** [comment]
I have no idea what could cause this and I cannot reproduce it. I just tried it on a fresh install with just Fabric Loader, Fabric API, and Traverse and it worked fine.

**Comment by Prospector** [comment]
Actually, I think your Traverse jar is broken, in the crash report it lists the version as `$version`. Try re-downloading it from CurseForge: https://www.curseforge.com/minecraft/mc-mods/traverse/files/3033950

**Comment by Prospector** [comment]
Oh, just figured it out. You must've downloaded the sources jar listed under "Additional Files"... I can see how that is confusing since they have the same title.
