### ISSUE TITLE
Buried Treasure can be overwritten when a biome with a beach is overwritten

### ISSUE THREAD

**Issue by winterdrake** [TerraformersMC/Traverse#4]
This is the second time we've found a buried treasure map where we simply COULD NOT find the treasure so I went into spectator mode to find the chest. There was absolutely no chest at the coordinates of the buried treasure map, nor was there any sand, because it was an autumnal woods biome. I have a feeling the treasure needs sand to spawn, so biomes that replace sandy shore biomes destroy the treasure.

**Comment by coderbot16** [comment]
I'm not sure this is actually a Traverse issue, Traverse only replaces the shores of one biome (the wooded island) - all others should generate shores like normal: https://github.com/TerraformersMC/Traverse/blob/1.14.4/src/main/java/com/terraformersmc/traverse/generation/TraverseGeneration.java

Are you 100% sure that there is no treasure? Make sure to check it in spectator mode / xray to be absolutely sure.

**Comment by winterdrake** [comment]
Welp you're correct, I sort of assumed it was an issue because I had only seen buried treasure in sand and there was no sand nearby, but upon second inspection with spec mode, there was treasure. My bad!

**Comment by coderbot16** [comment]
glad that there's no issue, had me concerned for a bit :P
