### ISSUE TITLE
Incompat. with Terrestria.

### ISSUE THREAD

**Issue by MagmaSlime123** [TerraformersMC/Traverse#43]
No crash report is given.

traverse-3.0.0+build.6
terrestria-2.1.4+build.26
fabric-api-0.24.3+build.414-1.16

No other mods are present.

Logs file if you need it:
[latest.log](https://github.com/TerraformersMC/Traverse/files/5469915/latest.log)

![image](https://user-images.githubusercontent.com/51277766/97791101-fb923800-1b8b-11eb-9802-1d607699af34.png)

**Comment by coderbot16** [comment]
Please update Terrestria to version 2.1.4, you have 2.1.2.

The incompatibility with 2.1.3 or later should probably be noted in the mod json file, but it's a bit too late for that now. This is caused by moving code internally from Terrestria to a common library mod.

**Comment by MagmaSlime123** [comment]
Tried 2.1.4. Same crash.

New logs file if needed.
[latest.log](https://github.com/TerraformersMC/Traverse/files/5469926/latest.log)

**Comment by coderbot16** [comment]
Cinderscapes also needs to be updated to 1.2.3 as well.

**Comment by MagmaSlime123** [comment]
Ah.

Yep, that fixed it.

Fabric reeeeeeaaaaally loves not giving crash reports...

**Comment by coderbot16** [comment]
It seems like crashes early in Minecraft startup don't result in a report, which kinda sucks. Maybe Fabric can fix this.

**Comment by MagmaSlime123** [comment]
Yep. You could try letting them know about it possibly.

**Comment by dandin87** [comment]
You also need to update Fabric API...
