### ISSUE TITLE
Cliffs aren't snowy

### ISSUE THREAD

**Issue by luciobortoletto** [TerraformersMC/Traverse#49]
In **every** cliff there is no snow and if I set the weather to rain, it doesn't snows but it rains.
Demonstration video:
[![Cliffs aren't snowy](https://res.cloudinary.com/marcomontalbano/image/upload/v1608399853/video_to_markdown/images/video--9311ad456a0c83516b3994e1cbc11a1e-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://i.imgur.com/JqPOC25.mp4 "Cliffs aren't snowy") (if the video doesn't show, the link is https://imgur.com/a/OItJc6i )
I need help as soon as possible, because I need to use this mod in my modpack.

**Comment by Prospector** [comment]
It was intentional that this happened, however in the latest update I added Snowy Cliffs which spawn in Snowy climates which have snow on them.
