### ISSUE TITLE
There's no Fir Boat

### ISSUE THREAD

**Issue by luciobortoletto** [TerraformersMC/Traverse#51]
There's no Fir Boat

**Comment by coderbot16** [comment]
This is the repository for the Fabric version of Traverse, which should have a fir boat. Are you on the Forge version?

**Comment by luciobortoletto** [comment]
I'm on Fabric, with Traverse 3.2.0 build 17

**Comment by luciobortoletto** [comment]
Will this be fixed?

**Comment by Prospector** [comment]
I'm gonna need some more information like a log (with mod list and stuff). I can't reproduce the issue. What exactly do you mean by there's no fir boat? Does the item not exist? Does the entity not exist? Can you /give yourself a traverse:fir_boat? Is there just no recipe? Not in creative menu? 
![image](https://user-images.githubusercontent.com/6166773/104495579-c98a5280-558c-11eb-8c07-345902abea19.png)

**Comment by luciobortoletto** [comment]
I updated Fabric API and now there is the Fir Boat. Before doing this, it didn't exist (not even the item)
