### ISSUE TITLE
Autumnal Woods biomes do not have precipitation explicitly defined

### ISSUE THREAD

**Issue by FewerFlaws** [TerraformersMC/Traverse#54]
The code for [autumnal woods biomes](https://github.com/TerraformersMC/Traverse/blob/1.16.3/src/main/java/com/terraformersmc/traverse/biome/AutumnalWoodsBiomes.java) does not explicitly define a precipitation value.  But it appears to take a default value of "rain."  Low priority bug.

**Comment by FewerFlaws** [comment]
Eh, upon reviewing some other biomes I see there's others that leave it at default.  I'm guessing this is intended.

**Comment by Prospector** [comment]
Yeah, precipitation is defined here: TraverseBiomes.BIOME_TEMPLATE

**Comment by FewerFlaws** [comment]
Yep, I eventually found that.  Sorry for opening the issue too early =P
