### ISSUE TITLE
Zombie weights are slightly off in Arid Highlands

### ISSUE THREAD

**Issue by FewerFlaws** [TerraformersMC/Traverse#57]
In Vanilla zombie weights are set to simulate 5% of regular zombies getting converted to zombie villagers.  This behavior is maintained in deserts where 80% of regular zombies are converted to husks.  With that in mind, arid highlands should have the following weights:

zombies: 38
zombie villagers: 2

**Comment by Prospector** [comment]
Fixed in https://github.com/TerraformersMC/Traverse/commit/013a97a6172ece6dc6140b85fa281f53fbf312dd (referenced the wrong issue)
