### ISSUE TITLE
World generation issues

### ISSUE THREAD

**Issue by Panduino** [TerraformersMC/Traverse#59]
Chunks will generate oddly, harshly switching biomes and the like. I currently have another world generation mod installled, however it was doing the same before I installed that mod
![2021-02-05_17 24 20](https://user-images.githubusercontent.com/59328953/107095633-27e6d180-67d7-11eb-95fe-050b5d83d8d6.png)
![2021-02-05_17 24 41](https://user-images.githubusercontent.com/59328953/107095635-287f6800-67d7-11eb-97ba-ac2ca83a9384.png)
Using traverse 3.3.0 and terrestria 2.1.5 with biome makeover

**Comment by Prospector** [comment]
Have you been adding or removing mods since you initially created this world, or did they do this without you changing the mod set at all?

**Comment by Panduino** [comment]
> Have you been adding or removing mods since you initially created this world, or did they do this without you changing the mod set at all?

It's been doing this without adding mods.
Whats strange is that it only happens on my multiplayer server, but not in singleplayer

**Comment by coderbot16** [comment]
There's a somewhat major design flaw in Fabric API that means that if you change the order that biome mods are loaded in, you can get weird issues like this. This is much more likely if you have lots of biome mods, since all it takes is one of the mods to get loaded in a different order relative to other mods for stuff like this to happen.

Adding, updating, or removing *any* mod could change the mod load order, and thus the load order of biome mods, so things are somewhat sensitive here.

I'd be surprised if this wasn't related to adding, removing, or updating mods on the server.

**Comment by Panduino** [comment]
> There's a somewhat major design flaw in Fabric API that means that if you change the order that biome mods are loaded in, you can get weird issues like this. This is much more likely if you have lots of biome mods, since all it takes is one of the mods to get loaded in a different order relative to other mods for stuff like this to happen.
> 
> Adding, updating, or removing _any_ mod could change the mod load order, and thus the load order of biome mods, so things are somewhat sensitive here.
> 
> I'd be surprised if this wasn't related to adding, removing, or updating mods on the server.

Haven't changed a thing since the server started and the world was created

**Comment by coderbot16** [comment]
So did you completely recreate the world when you added the new mod?

> I currently have another world generation mod installled, however it was doing the same before I installed that mod

**Comment by Panduino** [comment]
> So did you completely recreate the world when you added the new mod?
> 
> > I currently have another world generation mod installled, however it was doing the same before I installed that mod

Yes, we created a new world when we added new mods

**Comment by coderbot16** [comment]
Hmm, this is odd.

Can you send a log file? Latest.log is fine.

**Comment by coderbot16** [comment]
We'll need a log file (or at the very least, a mod list) to investigate this issue any further
