### ISSUE TITLE
how to get the json biome files ?

### ISSUE THREAD

**Issue by Chuunkyz** [TerraformersMC/Traverse#63]
Hi,
I'm making a modpack and i need the json of some biomes, to modify various things in the worldgen.
Oh The Biomes You'll Go adds a /gendata command to get the json files of every biome and configured features, but when i use the command on a world with just Byg and Traverse, there's no biome in the biome folder of traverse (and i also have the same problem with terrestria).
I know i can write the json myself using the source code of the biomes, but is there an easier way to do that ?

**Comment by Prospector** [comment]
Hm, that's weird. I've used that command in the past on Traverse biomes and it seemed to work.

**Comment by Chuunkyz** [comment]
What mods do you used to use the /gendata command ? Only Byg and Traverse ? And also what fabric version ?
btw when i use the command '/gendata traverse' the game says 'an error occured trying to execute that command'
i have a traverse-custom folder but with only the configured features

**Comment by Chuunkyz** [comment]
Hi, i downgraded byg 1.1.7 to 1.1.3 and it worked fine ;)
this was not a traverse bug so sorry for the inconvenience ^^
