### ISSUE TITLE
Meadow biome map bug

### ISSUE THREAD

**Issue by VulpiniLagopus** [TerraformersMC/Traverse#64]
On vanilla Minecraft map, the meadow biome looks like this
![2021-04-29_13 55 34](https://user-images.githubusercontent.com/83270965/116546986-975df000-a8f2-11eb-8568-683b81142054.png)
Even though the biome looks like this:
![2021-04-29_13 56 43](https://user-images.githubusercontent.com/83270965/116547109-bfe5ea00-a8f2-11eb-8402-a2df2b1327f2.png)

**Comment by Prospector** [comment]
Hm, I cannot reproduce. It may be another mod messing with maps. 
![image](https://user-images.githubusercontent.com/6166773/126572589-72adff63-1784-4ea9-9678-f6b8edc955e8.png)
