### ISSUE TITLE
Rolling Hills generation does not obey configuration file

### ISSUE THREAD

**Issue by itsNordLord** [TerraformersMC/Traverse#65]
Version `traverse-3.3.2` and `fabric-api-0.34.2+1.16`

![image](https://user-images.githubusercontent.com/68762570/120085299-dca94500-c08b-11eb-9d11-8a71b4cb0c57.png)

**Comment by Prospector** [comment]
This is sorta intended, actually. The way Cliffs work is that they generate an outer wall and then inner parts of the Cliffs are replaced with Rolling Hills. If they didn't do this, there would be a really weird and ugly looking stone plateau at the top. If you don't want to see this, disable the Cliffs biome as well.
