### ISSUE TITLE
Autumnal leaves drop themselves instead of saplings, etc.

### ISSUE THREAD

**Issue by Mysteriaa** [TerraformersMC/Traverse#70]
Basically what the title says. I can't get saplings from autumnal trees because it keeps dropping the leaf blocks instead of saplings and the like. i haven't checked this with the mod's other trees.

**Comment by TritonJ73** [comment]
Yeah i get the same thing for fir tree leaves

**Comment by Prospector** [comment]
On 1.17? What version of the mod? Make sure to include critical information in issues.

**Comment by TritonJ73** [comment]
1.17.1 traverse v4.0.0-beta.1

**Comment by lils30** [comment]
I have the same issue, so i decided to test it and its the same with all the trees, they all drop their leaves instead of sapplings

**Comment by jhbuchanan45** [comment]
I know what the issue is, I have it fixed on a local copy. Something slightly changed with the format of the loot tables that makes the shears requirement for leaves to drop themselves not work properly
