### ISSUE TITLE
Brown Autmn Tree Saplings dont drop

### ISSUE THREAD

**Issue by Daihok41** [TerraformersMC/Traverse#72]
The newest 1.17 v4.0.0 On the brown autumn trees when ya cut down tree the leaves fall instead of saplings.

**Comment by jhbuchanan45** [comment]
So I remember spotting this in testing my fix, so I went back and checked my test world... turns out I tested my fix for brown autumnal trees on red ones. :facepalm: Perks of being colorblind I guess. I'll make a PR with the fixed version in a few minutes, once I _actually_ verify it works
