### ISSUE TITLE
Decided to bite the bullet and see what would happen if I ran this mod against my WIP pack. Incompatible with Terrablender.

### ISSUE THREAD

**Issue by Sunconure11** [TerraformersMC/Traverse#82]
https://pastebin.com/Ln8TbhCp

https://pastebin.com/uGdXG3nH

**Comment by Prospector** [comment]
Whoops, I know the problem

**Comment by Prospector** [comment]
Let me know how it goes with 5.0.0-alpha.2 https://modrinth.com/mod/traverse/version/fzIjr6Tn

**Comment by Sunconure11** [comment]
Works
