### ISSUE TITLE
Significant fps drop in some biomes

### ISSUE THREAD

**Issue by Lozf** [TerraformersMC/Traverse#89]
So I was testing some animal spawning configs and noticed significant fps drops in traverse biomes coniferous forest and snowy coniferous forests- going down to 30ish fps, although occasionally they are up to my normal 70-80 - but only in the snowy coniferous.  Mostly they hang around 40.  The other traverse biomes I've come across- flatlands, woodlands, and autumnal woods are all running around 80-100+.  Just wanted to let you know in case it was something weird!  I love this mod so much!  It's gorgeous.

**Comment by gniftygnome** [comment]
Can you tell if this is related to generating new chunks or if it just happens all the time?  Nothing immediately comes to mind (I was actually more concerned about the sandy biomes) but I'll look around some more.

**Comment by gniftygnome** [comment]
In testing (and this may be graphics card dependent, but I am testing with the crappy Intel one), I am not seeing any real difference between those biomes and other biomes.  The behavior in Mega Taiga biomes in particular is practically identical to the Traverse Coniferous forests.  One easy way to cause major FPS drops though is to go in spectator and move around underground.  Likewise, passing through a lot of tree canopies above ground causes FPS drops down to 20 or so on my system, like clockwork.

**Comment by gniftygnome** [comment]
I would be curious to know what other mods are installed, if any (besides FAPI and TerraBlender, of course).

**Comment by Lozf** [comment]
A lot of mods, heh.  I can do some testing when I get home.  It seemed to be all the time.  I get around 70-80 fps continuously in Mega Taiga biomes.

**Comment by gniftygnome** [comment]
It could easily be an interaction with things like Better Leaves or Sodium I suppose.  Although I'd more suspect Terrestria of that than Traverse.

**Comment by Lozf** [comment]
You were right!  I forgot about using Better Leaves- taking that off popped the fps up to 80ish.  I use sodium as well + indium and continuity.

**Comment by gniftygnome** [comment]
I like Better Leaves, but I've always used it together with Cull Leaves.
https://modrinth.com/mod/cull-leaves
https://www.curseforge.com/minecraft/mc-mods/cull-leaves

**Comment by Lozf** [comment]
I was using Cull Less Leaves, but I don't think it was affecting better leaves, just vanilla ones.  I'll try the Cull Leaves.

**Comment by Lozf** [comment]
Yup, that seems to have done it.  Went up to the upper 60s from 40s, that's just awesome.  And the leaves still look great!  Thanks!

**Comment by gniftygnome** [comment]
Awesome; this probably applies to Terrestria as well.  The canopies are just so large and dense...
