### ISSUE TITLE
Fabric 1.18.2, version 5.1.3 of Traverse, it does not rain in the Flatlands biome.

### ISSUE THREAD

**Issue by ChrisLensFlare** [TerraformersMC/Traverse#90]
Just that, doesn't rain in the flatlands biome.

**Comment by gniftygnome** [comment]
Thanks for this report; I'll look into it.

**Comment by gniftygnome** [comment]
This is caused by a really neat (from a programming perspective) misstep in the 1.18 port.  I will be releasing Traverse updates to fix it soon.  Some other minor aspects of a few biomes (such as grass or sky color) may change if they were incorrect for the same reason.
