### ISSUE TITLE
Traverse leaves and saplings can't be composted

### ISSUE THREAD

**Issue by slavalamp** [TerraformersMC/Traverse#91]
same issue with terrestria i think

**Comment by gniftygnome** [comment]
Terrestria does register compostables, so this is just in Traverse.  (There are a few desert plants Terrestria does not register, which is perhaps a debatable decision; we'll discuss it.)

This is pretty easy to fix for Traverse but I need to checkpoint my work on Traverse for 1.19.3 so it'll have to wait until I have a bit of free time (this weekend, probably).

**Comment by gniftygnome** [comment]
This is fixed in Traverse 6.0.6 for Minecraft 1.19.x.  1.18.2 was not broken.  I'll work on getting more things to compost in Terrestria.
