### ISSUE TITLE
All Custom Block which do not copy their properties from Vanilla Blocks are missing their Tags

### ISSUE THREAD

**Issue by AwesomeDude091** [TerraformersMC/Traverse#98]
Hello, I noticed that some of the items / blocks from this mod are not working with other mods due to incompatibility issues, upon further investigation I discovered that some items / blocks are missing their vanilla block properties

For example the Fir Plank copies Oak Plank's properties, Fir Log or Stripped Fir Log do not, as such cross compatibility with other mod is not present with Fir Logs and Stripped Fir Logs, while Oak Planks work. 

The fix would be to add the vanilla tags to these items / blocks or to make those items / blocks also copy properties from oak equivalents

Cheers, AwesomeDude091

P.S. Huge fan of this mod and would love if it were fully compatible with other mods :))

**Comment by AwesomeDude091** [comment]
If this fix is applied, for what versions would it be applied?

**Comment by gniftygnome** [comment]
Could you be a bit more specific about what other mod(s) you are referring to?  I'm not disbelieving the problem, it would just make it easier for me to find out what kinds of properties are missing.

**Comment by AwesomeDude091** [comment]
After further investigation I think I have found the root of the bug. I think it is an issue with the Vanilla Tags which a lot of mods use to generally group item / block types. When an item / a block has the `FabricBlockSettings.copyOf(Blocks.Vanilla_Block_Here)` it seems to also copy the Tags, the blocks which do not use this setting, do not have their matching tags. 

I was able to see this bug using the Create Mod. Crafting recipies involving planks worked fine because Fir Planks inherit from Oak Planks (Have the Plank Tag), whereas Crafting Recipies involving Stripped Logs did not work because they do not inherit from Stripped Oak Logs (Have the Stripped Log Tag)

Specific Crafting Recipies used: Crafting a Cogwheel ; Crafting an Andesite Casing

Note I think that the blocks behave more or less as they should, they are just missing these groupings to make them complete.

Hope this helps, AwesomeDude091

**Comment by gniftygnome** [comment]
What version of Minecraft are you testing with and what version of Traverse / Terrestria?

**Comment by AwesomeDude091** [comment]
I was testing on Version 1.19.2, latest build

**Comment by AwesomeDude091** [comment]
To be more specific in the 1.20 version I think the issue is that some blocks do not inherit and in 1.19.2 the issue is that the stripped log inherits from `FabricBlockSettings.copyOf(Blocks.OAK_LOG)` not the `STRIPPED_OAK_LOG`

**Comment by gniftygnome** [comment]
OK, the tag they are using is c:stripped_logs, which is not defined in Fabric's ConventionalItemTags even in the latest 1.20 versions.  Generally we do not define conventional tags that are not included in Fabric.  What I can do is add a few more one-off conventional tags, if you can give me a list of recipes you've noticed are not working.  I would backport this change to 1.19.4 and 1.19 (which includes .1 and .2) but probably not to 1.19.3 which I consider largely abandoned.

**Comment by AwesomeDude091** [comment]
I will investigate and report back :))

The one I can already confirm right now is Stripped Logs.

Thank you going out of your way to add this support :))

**Comment by gniftygnome** [comment]
I see we also need c:stripped_wood and for bonus points could define c:stone (Terrestria's volcanic rock).  Not an exhaustive check yet though; Create has a huge pile of recipes.

**Comment by AwesomeDude091** [comment]
Stripped Logs were the only thing I could find, thank you so much. Also will this be added to Terrestria and Cinderscapes?

**Comment by gniftygnome** [comment]
> Also will this be added to Terrestria and Cinderscapes?

Yes.

**Comment by gniftygnome** [comment]
Resolved in 6.0.7, 6.2.2, and 7.0.1.
