### ISSUE TITLE
Crash when accessing creative inventory

### ISSUE THREAD

**Issue by ghost** [TerraformersMC/Traverse#99]
Minecraft 1.20
Fabric API 0.83.0+1.20
Traverse 7.0.3
no other mods

[crash-2023-06-16_13.49.14-client.txt](https://github.com/TerraformersMC/Traverse/files/11765851/crash-2023-06-16_13.49.14-client.txt)
[latest.log](https://github.com/TerraformersMC/Traverse/files/11765854/latest.log)

**Comment by gniftygnome** [comment]
"Whoops..."
